### ISSUE TITLE
Omit certain dates

### ISSUE THREAD

**Issue by Bumbleboss** [PawanKolhe/color-calendar#13]
Does this have the ability to hide certain dates?
I want the user to only be able to select x, y date but not z date. 

Right now the unselectable dates are the ones that aren't in the same month

**Comment by Bumbleboss** [comment]
Found my own solution so I'll close this issue.
For anyone who's interested, I used the events data to manipulate the elements.

**Comment by afzalzbr** [comment]
@Bumbleboss can you elaborate on how you did that?
I want to disable the dates prior to today.
