### ISSUE TITLE
Can you make usage guidelines for react?

### ISSUE THREAD

**Issue by JoshuaPoddoku** [PawanKolhe/color-calendar#2]
An example can help! Thanks

**Comment by PawanKolhe** [comment]
@JoshuaPoddoku Here is a way to use color-calendar in React:
https://codesandbox.io/s/color-calendar-react-y0cyf?file=/src/CalendarComponent.jsx

You can create a new component with color-calendar imported and render the html element for the calendar `<div id="myCal"></div>`. Then create an instance in the `componentDidMount()` lifecycle method.
